# fly.toml app configuration file generated for gate-opener-cloud on 2023-07-25T12:15:42-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gate-opener-cloud"
primary_region = "sea"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
