services:
  agent:
    container_name: gate_controller_agent
    build: .
    environment:
      GATE_CONTROLLER_AGENT_TOKEN: ${GATE_CONTROLLER_AGENT_TOKEN:-}
    volumes:
      - ./:/workspace
      - /dev/mem:/dev/mem
    privileged: true # required for /dev/mem passthrough
    command: python /workspace/main.py
    restart: always
